version: "3"
      
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8090:8080" # HTTP proxy
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      #- OPENVPN_USER=
      #- OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=<PUT UR PRIVATE KEY HERE INNIT>
      - WIREGUARD_ADDRESSES=
      - SERVER_COUNTRIES= <PUT UR COUNTRY HERE INNIT>
      # Timezone for accurate log times
      #- TZ=
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      #- UPDATER_PERIOD=  
#Radarr - used to find movies automatically
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_hosts/radar/config:/config
      - /share:/share #Access to the entire share
    #networks: #Does not connect to overseer if you use NPM
    #  - proxy
    ports:
      - 7878:7878
    restart: unless-stopped
    
  #Sonarr - used to find tv shows automatically
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_hosts/sonar/config:/config
      - /share:/share #Access to the entire share
    #networks: #Does not connect to overseer if you use NPM
    #  - proxy
    ports:
      - 8989:8989
    restart: unless-stopped


  #Overseer - allows users to request media on their own
  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_hosts/overseer/config:/config
      - /share:/share #Access to the entire share
    #networks:
    #  - proxy
    ports:
      - 5055:5055
    restart: unless-stopped

  #Qbittorent - torrenting software
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=8694
    volumes:
      - /docker_hosts/qbittorent/config:/config
      - /share:/share
    restart: unless-stopped


  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /path/to/jackett/data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  ##jellyfin
  jellyfin:
      image: jellyfin/jellyfin
      container_name: jellyfin
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - /docker_hosts/config:/config
        - /docker_hosts/cache:/cache
        - /share:/media
      ports:
        - 8096:8096
      restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker_hosts/lidarr/config:/config
      - /share:/share # Access to your music/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    environment:
      - TZ=Etc/UTC
      - ND_SPOTIFY_ID=<PUT UR CLIENT KEY HERE INNIT>
      - ND_SPOTIFY_SECRET=<PUT UR SECRET KEY HERE INNIT>
      - ND_AUTOIMPORTPLAYLISTS=false
    user: 1000:1000
    volumes:
      - /docker_hosts/navidrome:/data # DB and Cache stored here
      - /share/media/music:/music:ro                 # :ro = Read Only (Safe for library)
    ports:
      - 4533:4533
    restart: unless-stopped
